### ISSUE TITLE
Key null bug for highlevel roundrobin producer

### ISSUE THREAD

**Issue by ChristianTrolleMikkelsen** [mvno/Franz#61]
RoundRobin producer can hit a case where topicName appears to be null (see below).
Apparently this happens on retry due to request timeout.
Maybe a metadata race condition?
Anyway we should proberbly handle it and do a metadata refresh to get updated partition information.

System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Franz.HighLevel.RoundRobinProducer.getNextPartitionId[a](String topicName, a _arg1)
   at <StartupCode$Franz>.$HighLevel.-ctor@189-37.Invoke(String arg1, String arg2)
   at Franz.HighLevel.BaseProducer.send(String key, String topicName, MessageSet[] messages, RequiredAcks requiredAcks, Int32 brokerProcessingTimeout, Int32 retryCount)
   at <StartupCode$Franz>.$HighLevel.clo@72-23.Invoke(Unit unitVar0)
   at Franz.HighLevel.BaseProducer.retryOnRequestTimedOut[a](FSharpFunc`2 retrySendFunction, Int32 retryCount)
   at Franz.HighLevel.BaseProducer.send(String key, String topicName, MessageSet[] messages, RequiredAcks requiredAcks, Int32 brokerProcessingTimeout, Int32 retryCount)
   at Franz.HighLevel.BaseProducer.sendMessages(String key, String topic, RequiredAcks requiredAcks, Int32 brokerProcessingTimeout, IEnumerable`1 messages)
   at <StartupCode$Franz>.$HighLevel.SendMessages@98.Invoke(Tuple`2 tupledArg)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at Franz.HighLevel.BaseProducer.SendMessages(String topic, Message[] messages, RequiredAcks requiredAcks, Int32 brokerProcessingTimeout)
   at Franz.HighLevel.RoundRobinProducer.SendMessages(String topicName, Message[] messages, RequiredAcks requiredAcks, Int32 brokerProcessingTimeout)
   at Franz.HighLevel.RoundRobinProducer.Franz-HighLevel-IProducer-SendMessages(String topicName, Message[] messages, RequiredAcks requiredAcks, Int32 brokerProcessingTimeout)

**Comment by ChristianTrolleMikkelsen** [comment]
#62

**Comment by ChristianTrolleMikkelsen** [comment]
I can see now that it is a mishap during refactor. https://github.com/mvno/Franz/commit/1a0181b1e48387c1c56682e898b20756f4925d7d

**Comment by kichristensen** [comment]
Fixed in #62
